name: auto-update

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
        name: Set up Bun cache
        with:
          path: |
            ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Automatic update
        run: bun tools/auto-update.mjs

      - name: Push latest version
        uses: GuillaumeFalourd/git-commit-push@205c043bca2f932f7a48a28a8d619ba30eb84baf # v1.3
        with:
          name: "auto-update"
          commit_message: "automatic update"
          files: "bucket/playdate-sdk.json"
