name: auto-update

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 1

      - name: Setup Bun
        uses: oven-sh/setup-bun@a1800f471a0bc25cddac36bb13e6f436ddf341d7 # v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Automatic update
        run: bun tools/auto-update.mjs

      - name: Push latest version
        uses: GuillaumeFalourd/git-commit-push@205c043bca2f932f7a48a28a8d619ba30eb84baf # v1.3
        with:
          name: "auto-update"
          commit_message: "automatic update"
          files: "bucket/playdate-sdk.json"

      - uses: gautamkrishnar/keepalive-workflow@05456e7809058d586d96392e99217726ccc10076 # v2.0.5
        with:
          commit_message: "keep alive"
          committer_username: "GitHub Action"
          committer_email: "action@users.noreply.github.com"
          gh_token: "${{ secrets.GITHUB_TOKEN }}"
